# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
---
_commit: v1.2.1
_src_path: https://github.com/hasansezertasan/copier-pyproject.git
author_email: hasansezertasan@gmail.com
author_family_names: Tasan
author_full_name: Hasan Sezer Tasan
author_given_names: Hasan Sezer
cli_framework: typer
github_repo_name: ocom
github_user: hasansezertasan
include_all_contributors: false
include_c_extensions: false
include_cli: true
include_compiler: false
include_dbeaver: false
include_examples: false
include_freezer: false
include_gui: false
include_homebrew: true
include_launcher: false
include_mcp: false
include_megalinter: false
include_postgres: false
include_profiling: false
include_pydantic_settings: true
include_redis: false
include_repo_ruleset: false
include_repo_settings: true
include_scoop: true
include_sonarcloud: false
include_sourcery: false
include_tui: true
include_vpn: false
include_web: false
include_worker: false
package_keywords: tui, vpn, openvpn, warp, spoofdpi, goodbyedpi, network, privacy
preset: tool
repository_topics: tui, textual, python, python-tui, cli, typer, vpn, openvpn, cloudflare-warp,
    tailscale, spoofdpi, goodbyedpi, dpi-bypass, censorship-circumvention, networking,
    network-tools, vpn-manager, privacy, terminal, cross-platform
short_description: 'A unified TUI for managing network/privacy tools: OpenVPN, SpoofDPI,
    Cloudflare WARP'
